### ISSUE TITLE
Mas mau tanya nih ? tolong di jawab.

### ISSUE THREAD

**Issue by dwindibudimulia** [agustiyann/movie-catalogue-api#1]
String poster= object.getString("poster_path" );
            this.posterPath = "https://image.tmdb.org/t/p/w185/" + poster;

utk ngambil string posternya dari mna ya mas saya bingung. saya cari2 tidak ada di string.xml
Terima kasih

**Comment by agustiyann** [comment]
string poster yang "poster_path" ?? itu manggil object JSON yang disediakan sama themoviedb mas.
